## Path
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods/
  - .build/
  - .git/
  - .swiftpm/
  - Package.swift
included: # paths to include during linting. `--path` is ignored if present.
  - YourFamily
## Enabled Rule
# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
  - trailing_comma #
  - todo #
  - multiple_closures_with_trailing_closure #
  - class_delegate_protocol #
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  # Coding Rule Category
  - closure_spacing
  - collection_alignment
  - explicit_self
  - extension_access_modifier
  - file_header
#  - file_types_order
#  - implicit_return
  - indentation_width
  - legacy_multiple
  - legacy_objc_type
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - operator_usage_whitespace
  - override_in_extension
  - private_action
  - private_outlet
  - sorted_imports
  - trailing_closure
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
#  - type_contents_order https://github.com/realm/SwiftLint/issues/3548

  # SwiftLint Repository
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
#  - closure_spacing # In Coding Rule Category
#  - collection_alignment # In Coding Rule Category
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_none_name
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
#  - empty_xctest_method # Xcode13 https://github.com/realm/SwiftLint/issues/3647
  - enum_case_associated_values_count
  - explicit_init
#  - extension_access_modifier # In Coding Rule Category
  - fallthrough
  - fatal_error_message
#  - file_header # In Coding Rule Category
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
#  - legacy_multiple # In Coding Rule Category
#  - legacy_random # In Coding Rule Category
#  - literal_expression_end_indentation # In Coding Rule Category
#  - lower_acl_than_parent # In Coding Rule Category
#  - modifier_order # In Coding Rule Category
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
#  - operator_usage_whitespace # In Coding Rule Category
  - overridden_super_call
#  - override_in_extension # In Coding Rule Category
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
#  - private_action # In Coding Rule Category
#  - private_outlet # In Coding Rule Category
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
#  - redundant_type_annotation # In Coding Rule Category
  - single_test_class
  - sorted_first_last
#  - sorted_imports # In Coding Rule Category
  - static_operator
  - strong_iboutlet
  - test_case_accessibility
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Alternatively, s6ecify all rules explicitly by uncommenting this option:
# only_rules: # delete `disabled_rules` & `opt_in_rules` if using this
#   - empty_parameters
#   - vertical_whitespace

# analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
#  - unused_declaration
#  - unused_import

## Rule Configuration
file_header:
  required_pattern: |
                    \/\/
                    \/\/ Created by iletai.
                    \/\/
file_name:
  excluded:
    - main.swift
    - LinuxMain.swift
    - TestHelpers.swift
    - shim.swift
    - AutomaticRuleTests.generated.swift
    - Persistence.swift
identifier_name:
  excluded:
    - x
    - y
    - z
    - i
    - j
    - k
    - n
    - id
    - up
    - on
# line_length: 100 # default 120
number_separator:
  minimum_length: 5
#trailing_comma:
#  mandatory_comma: true
